Vagrant.configure("2") do |config|
  # Définir la box de base
  config.vm.box = "ubuntu/bionic64" # Utilise Ubuntu 18.04 LTS. Tu peux changer cela selon tes besoins.

  # Définir le nom de la VM
  config.vm.hostname = "soutenance"

  # Configuration de la machine virtuelle
  config.vm.network "forwarded_port", guest: 22, host: 2224 # Redirige le port SSH

  config.vm.network "private_network", ip: "192.168.33.10"

  # Montage d'un répertoire de l'hôte vers la VM
  config.vm.synced_folder "~/Desktop/Lab", "/mnt/lab", type: "virtualbox"

  # Provisionnement pour installer Docker
  config.vm.provision "shell", inline: <<-SHELL
    # Mettre à jour les paquets
    sudo apt-get update

    # Installer les dépendances pour Docker
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

    # Ajouter la clé GPG de Docker
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    # Ajouter le dépôt Docker
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    # Mettre à jour les paquets à nouveau
    sudo apt-get update

    # Installer Docker
    sudo apt-get install -y docker-ce

    # Ajouter l'utilisateur vagrant au groupe docker (pour éviter d'utiliser sudo avec docker)
    sudo usermod -aG docker vagrant

    # Vérifier l'installation de Docker
    docker --version
  SHELL

  # Configuration de la VM pour VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192" # Définir la mémoire à 8 Go
    vb.cpus = 8        # Définir le nombre de cœurs CPU à 8
  end
end
